$jsonStr = [System.IO.File]::ReadAllText("glagoljasko_pjevanje_lokacije.json", [System.Text.Encoding]::UTF8)

# Post-processing the JSON with specific known mojibake -> croatian characters replacements 
# specific to the text observed

$jsonStr = $jsonStr -replace 'BAGALOVI', 'BAGALOVIĆ'
$jsonStr = $jsonStr -replace 'BAKA', 'BAŠKA'
$jsonStr = $jsonStr -replace 'BOGOVII', 'BOGOVIĆI'
$jsonStr = $jsonStr -replace 'BOGOVII \(DUBANICA\)', 'BOGOVIĆI (DUBAŠNICA)'
$jsonStr = $jsonStr -replace 'DUBANICA', 'DUBAŠNICA'
$jsonStr = $jsonStr -replace 'ARA', 'ČARA'
$jsonStr = $jsonStr -replace 'RAIE', 'RAČIŠĆE'
$jsonStr = $jsonStr -replace 'VRLJEVO', 'ČVRLJEVO'
$jsonStr = $jsonStr -replace 'APLJINA', 'ČAPLJINA'
$jsonStr = $jsonStr -replace 'DRANICE', 'DRAŠNICE'
$jsonStr = $jsonStr -replace 'DUE - ROGA', 'DUĆE - ROGAČ'
$jsonStr = $jsonStr -replace 'GORNJE SELO \(OTOK OLTA\)', 'GORNJE SELO (OTOK ŠOLTA)'
$jsonStr = $jsonStr -replace 'KATEL', 'KAŠTEL'
$jsonStr = $jsonStr -replace 'LUKI', 'LUKŠIĆ'
$jsonStr = $jsonStr -replace 'SUURAC', 'SUĆURAC'
$jsonStr = $jsonStr -replace 'TAFILI', 'ŠTAFILIĆ'
$jsonStr = $jsonStr -replace 'KATELA', 'KAŠTELA'
$jsonStr = $jsonStr -replace 'KREEVO', 'KREŠEVO'
$jsonStr = $jsonStr -replace 'KOMIA', 'KOMIŽA'
$jsonStr = $jsonStr -replace 'KORULA', 'KORČULA'
$jsonStr = $jsonStr -replace 'LANIE', 'LANIŠĆE'
$jsonStr = $jsonStr -replace 'LIANE OSTROVIKE', 'LIŠANE OSTROVIČKE'
$jsonStr = $jsonStr -replace 'LOKVIII', 'LOKVIČIĆI'
$jsonStr = $jsonStr -replace 'METKOVI', 'METKOVIĆ'
$jsonStr = $jsonStr -replace 'MIRLOVI', 'MIRLOVIĆ'
$jsonStr = $jsonStr -replace 'NEREIA', 'NEREŽIŠĆA'
$jsonStr = $jsonStr -replace 'OMIALJ', 'OMIŠALJ'
$jsonStr = $jsonStr -replace 'PRVI', 'PRVIĆ'
$jsonStr = $jsonStr -replace 'EPURINE', 'ŠEPURINE'
$jsonStr = $jsonStr -replace 'PELJEAC', 'PELJEŠAC'
$jsonStr = $jsonStr -replace 'PETRANE', 'PETRČANE'
$jsonStr = $jsonStr -replace 'PLOE', 'PLOČE'
$jsonStr = $jsonStr -replace 'PRANICE', 'PRAŽNICE'
$jsonStr = $jsonStr -replace 'PROLOAC', 'PROLOŽAC'
$jsonStr = $jsonStr -replace 'PUIA', 'PUČIŠĆA'
$jsonStr = $jsonStr -replace 'RADOI', 'RADOŠIĆ'
$jsonStr = $jsonStr -replace 'RIICE', 'RIČICE'
$jsonStr = $jsonStr -replace 'RUNOVI', 'RUNOVIĆ'
$jsonStr = $jsonStr -replace 'RUNOVII', 'RUNOVIĆI'
$jsonStr = $jsonStr -replace 'SUKOAN', 'SUKOŠAN'
$jsonStr = $jsonStr -replace 'SVIRE', 'SVIRČE'
$jsonStr = $jsonStr -replace 'KRIP', 'ŠKRIP'
$jsonStr = $jsonStr -replace 'VELI VARO', 'VELI VAROŠ'
$jsonStr = $jsonStr -replace 'ZADARSKO ZALEE', 'ZADARSKO ZALEĐE'
$jsonStr = $jsonStr -replace 'IVOGOE', 'ŽIVOGOŠĆE'
$jsonStr = $jsonStr -replace 'RNOVO', 'ŽRNOVO'
$jsonStr = $jsonStr -replace 'UPA', 'ŽUPA'
$jsonStr = $jsonStr -replace 'SKRPII', 'SKRPČIĆI'
$jsonStr = $jsonStr -replace 'PRIMOTEN', 'PRIMOŠTEN'

$jsonStr = $jsonStr -replace 'Slubenica Milosra', 'Službenica Milosrđa'
$jsonStr = $jsonStr -replace 'Anele', 'Anđele'
$jsonStr = $jsonStr -replace 'Cvitanovi', 'Cvitanović'
$jsonStr = $jsonStr -replace 'izriito', 'izričito'
$jsonStr = $jsonStr -replace 'prateih', 'pratećih'
$jsonStr = $jsonStr -replace 'izvoaima', 'izvođačima'
$jsonStr = $jsonStr -replace 'BURI', 'BURIĆ'
$jsonStr = $jsonStr -replace 'VEA', 'VEŽA'
$jsonStr = $jsonStr -replace 'KRNI', 'KRNIĆ'
$jsonStr = $jsonStr -replace 'BOO KOPLJANAC', 'BOŽO ŠKOPLJANAC'
$jsonStr = $jsonStr -replace 'IMUN UGURA', 'ŠIMUN ŽUGURA'

[System.IO.File]::WriteAllText("$pwd\glagoljasko_pjevanje_lokacije.json", $jsonStr, [System.Text.Encoding]::UTF8)

$csvStr = [System.IO.File]::ReadAllText("$pwd\glagoljasko_pjevanje_lokacije.csv", [System.Text.Encoding]::UTF8)
$csvStr = $csvStr -replace 'BAGALOVI', 'BAGALOVIĆ'
$csvStr = $csvStr -replace 'BAKA', 'BAŠKA'
$csvStr = $csvStr -replace 'BOGOVII', 'BOGOVIĆI'
$csvStr = $csvStr -replace 'BOGOVII \(DUBANICA\)', 'BOGOVIĆI (DUBAŠNICA)'
$csvStr = $csvStr -replace 'DUBANICA', 'DUBAŠNICA'
$csvStr = $csvStr -replace 'ARA', 'ČARA'
$csvStr = $csvStr -replace 'RAIE', 'RAČIŠĆE'
$csvStr = $csvStr -replace 'VRLJEVO', 'ČVRLJEVO'
$csvStr = $csvStr -replace 'APLJINA', 'ČAPLJINA'
$csvStr = $csvStr -replace 'DRANICE', 'DRAŠNICE'
$csvStr = $csvStr -replace 'DUE - ROGA', 'DUĆE - ROGAČ'
$csvStr = $csvStr -replace 'GORNJE SELO \(OTOK OLTA\)', 'GORNJE SELO (OTOK ŠOLTA)'
$csvStr = $csvStr -replace 'KATEL', 'KAŠTEL'
$csvStr = $csvStr -replace 'LUKI', 'LUKŠIĆ'
$csvStr = $csvStr -replace 'SUURAC', 'SUĆURAC'
$csvStr = $csvStr -replace 'TAFILI', 'ŠTAFILIĆ'
$csvStr = $csvStr -replace 'KATELA', 'KAŠTELA'
$csvStr = $csvStr -replace 'KREEVO', 'KREŠEVO'
$csvStr = $csvStr -replace 'KOMIA', 'KOMIŽA'
$csvStr = $csvStr -replace 'KORULA', 'KORČULA'
$csvStr = $csvStr -replace 'LANIE', 'LANIŠĆE'
$csvStr = $csvStr -replace 'LIANE OSTROVIKE', 'LIŠANE OSTROVIČKE'
$csvStr = $csvStr -replace 'LOKVIII', 'LOKVIČIĆI'
$csvStr = $csvStr -replace 'METKOVI', 'METKOVIĆ'
$csvStr = $csvStr -replace 'MIRLOVI', 'MIRLOVIĆ'
$csvStr = $csvStr -replace 'NEREIA', 'NEREŽIŠĆA'
$csvStr = $csvStr -replace 'OMIALJ', 'OMIŠALJ'
$csvStr = $csvStr -replace 'PRVI', 'PRVIĆ'
$csvStr = $csvStr -replace 'EPURINE', 'ŠEPURINE'
$csvStr = $csvStr -replace 'PELJEAC', 'PELJEŠAC'
$csvStr = $csvStr -replace 'PETRANE', 'PETRČANE'
$csvStr = $csvStr -replace 'PLOE', 'PLOČE'
$csvStr = $csvStr -replace 'PRANICE', 'PRAŽNICE'
$csvStr = $csvStr -replace 'PROLOAC', 'PROLOŽAC'
$csvStr = $csvStr -replace 'PUIA', 'PUČIŠĆA'
$csvStr = $csvStr -replace 'RADOI', 'RADOŠIĆ'
$csvStr = $csvStr -replace 'RIICE', 'RIČICE'
$csvStr = $csvStr -replace 'RUNOVI', 'RUNOVIĆ'
$csvStr = $csvStr -replace 'RUNOVII', 'RUNOVIĆI'
$csvStr = $csvStr -replace 'SUKOAN', 'SUKOŠAN'
$csvStr = $csvStr -replace 'SVIRE', 'SVIRČE'
$csvStr = $csvStr -replace 'KRIP', 'ŠKRIP'
$csvStr = $csvStr -replace 'VELI VARO', 'VELI VAROŠ'
$csvStr = $csvStr -replace 'ZADARSKO ZALEE', 'ZADARSKO ZALEĐE'
$csvStr = $csvStr -replace 'IVOGOE', 'ŽIVOGOŠĆE'
$csvStr = $csvStr -replace 'RNOVO', 'ŽRNOVO'
$csvStr = $csvStr -replace 'UPA', 'ŽUPA'
$csvStr = $csvStr -replace 'SKRPII', 'SKRPČIĆI'
$csvStr = $csvStr -replace 'PRIMOTEN', 'PRIMOŠTEN'

$csvStr = $csvStr -replace 'Slubenica Milosra', 'Službenica Milosrđa'
$csvStr = $csvStr -replace 'Anele', 'Anđele'
$csvStr = $csvStr -replace 'Cvitanovi', 'Cvitanović'
$csvStr = $csvStr -replace 'izriito', 'izričito'
$csvStr = $csvStr -replace 'prateih', 'pratećih'
$csvStr = $csvStr -replace 'izvoaima', 'izvođačima'
$csvStr = $csvStr -replace 'BURI', 'BURIĆ'
$csvStr = $csvStr -replace 'VEA', 'VEŽA'
$csvStr = $csvStr -replace 'KRNI', 'KRNIĆ'
$csvStr = $csvStr -replace 'BOO KOPLJANAC', 'BOŽO ŠKOPLJANAC'
$csvStr = $csvStr -replace 'IMUN UGURA', 'ŠIMUN ŽUGURA'

$csvStr = $csvStr -replace '\(MJESTO NIJE NAVEDENO\)', 'Nepoznato'
$csvStr = $csvStr -replace '\(MJESTO SNIMANJA NIJE NAVEDENO', 'Nepoznato'

[System.IO.File]::WriteAllText("$pwd\glagoljasko_pjevanje_lokacije.csv", $csvStr, [System.Text.Encoding]::UTF8)

Write-Host "Gotovo čišćenje."
